require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

target 'bitrisetest' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  
  pod 'AFNetworking', '~> 2.0'
  pod 'BBBadgeBarButtonItem'
  pod 'CAAnimation-EasingEquations'
  pod 'DAKeyboardControl'
  pod 'DateTools'
  pod 'FrameAccessor'
  pod 'JSONModel', '1.3.0'
  pod 'KVOController', '1.0.3'
  pod 'Masonry'
  pod 'RMMapper', '1.1.1'
  pod 'SnowplowTracker', '~> 1.7.0'
  pod 'TTTAttributedLabel'
  pod 'twitter-text-objc'
  pod 'UIAlertController+Blocks'
  pod 'Underscore.m', '0.2.1'
  pod 'L10n-swift', '~> 5.9'
  pod 'Nimble', '9.2.1'
  pod 'Quick', '2.2.1'
  pod 'SwiftDate', '5.1.0'

  # React Native: unsupported autolinking
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    #
    # Uncomment to opt-in to using Flipper
    # Note that if you have use_frameworks! enabled, Flipper will not work
    # :flipper_configuration => !ENV['CI'] ? FlipperConfiguration.enabled : FlipperConfiguration.disabled,
  )

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end

    # This post install script was required to build on a physical device using Xcode 14 beta 6. It prevents a signing error for 2 pods (TUSafariActivity and React-Core-AccessibilityResources) which states a development team is needed for the pods. This script sets the development team for the pods to our development team ("Dataminr, Inc.").
    # This may be an issue caused by the beta version of Xcode 14. If so, this script should be removed after Xcode 14 is out of beta.
    team_id = `grep export-archive.plist -e 'teamID' -A1 | grep string | sed -e 's/<[^>]*>//g'`.strip
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings["DEVELOPMENT_TEAM"] = team_id
            end
        end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
